# Generated by Django 5.2.3 on 2025-06-13 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("completed", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 6, 13, 4, 21, 23, 956431, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
        ),
    ]
