# Generated by Django 5.2.3 on 2025-06-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list", "0002_alter_task_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.CharField(
                choices=[("Work", "Work"), ("Peronal", "Personal"), ("Ohter", "Other")],
                default="Work",
                max_length=8,
            ),
        ),
    ]
