# Generated by Django 5.2.3 on 2025-06-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list", "0003_task_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.CharField(
                choices=[
                    ("Work", "Work"),
                    ("Peronal", "Personal"),
                    ("Play", "Play"),
                    ("Sleep", "Sleep"),
                    ("Wake-Up-Time", "Wake-Up"),
                    ("Ohter", "Other"),
                ],
                default="Work",
                max_length=12,
            ),
        ),
    ]
